import { auditCsv, stringifyCsv } from './csv-core.js';
const $=s=>document.querySelector(s); let latest=null;
const samples={
  'Clean contacts':'id,name,email\n1,Ada,ada@example.test\n2,Lin,lin@example.test\n',
  'Spreadsheet hazards':'id,name,note\n1,Ada,=SUM(A1:A2)\n1,Lin,"has\u0007 bell"\n,Sam,+123\n',
  'Quoted records':'id,comment\n1,"Line one\nline two, still one field"\n2,""\n',
  'Broken import':'name,name,amount\nAda,Ada,12\nLin,Lin,not sure\nSam,Sam\n'
};
function run(){ const text=$('#source').value; if(!text.trim()){ $('#empty').hidden=false; $('#report').hidden=true; return; } const pre=auditCsv(text); const select=$('#key'); select.innerHTML='<option value="">No key selected</option>'+pre.normalizedHeaders.map((h,i)=>`<option value="${i}">${escapeHtml(h)}</option>`).join(''); const prior=select.dataset.value; if(prior)select.value=prior; latest=auditCsv(text, select.value===''?-1:Number(select.value)); select.dataset.value=select.value; render(); }
function render(){const a=latest; $('#empty').hidden=true; $('#report').hidden=false; $('#summary').innerHTML=`<div><strong>${a.stats.records}</strong><span>data rows</span></div><div><strong>${a.stats.columns}</strong><span>columns</span></div><div class="bad"><strong>${a.stats.critical}</strong><span>blocking issues</span></div><div class="warn"><strong>${a.stats.warnings}</strong><span>review items</span></div>`; $('#detected').textContent=`Detected ${labelDelimiter(a.delimiter)} delimiter · ${a.safe?'Safe to export a normalized copy':'Export paused until row structure is repaired'}`; $('#findings').innerHTML=a.findings.length?a.findings.map(x=>`<li class="${x.severity}"><b>${x.severity==='critical'?'Blocking':'Review'}</b><span>${escapeHtml(x.code.replaceAll('_',' ').toLowerCase())}</span><p>${x.line?`Row ${x.line}${x.column!==undefined?`, ${a.normalizedHeaders[x.column]||'column '+(x.column+1)}`:''}: `:''}${escapeHtml(x.message)}</p></li>`).join(''):'<li class="good"><b>Clear</b><p>No data-quality issues were found by this audit.</p></li>'; const all=[a.normalizedHeaders,...a.rows]; $('#preview').innerHTML=all.slice(0,7).map((r,i)=>`<tr>${a.normalizedHeaders.map((_,j)=>`<${i?'td':'th'}>${escapeHtml(r[j]??'')}</${i?'td':'th'}>`).join('')}</tr>`).join(''); $('#previewNote').textContent=all.length>7?`Showing first 6 of ${a.stats.records} data rows.`:'Showing all data rows.'; $('#clean').disabled=!a.safe; }
function labelDelimiter(d){return d==='\t'?'tab':d===','?'comma':d===';'?'semicolon':'pipe';}
function escapeHtml(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('#source').addEventListener('input',run); $('#key').addEventListener('change',e=>{e.currentTarget.dataset.value=e.currentTarget.value;run();}); $('#file').addEventListener('change',async e=>{const f=e.target.files[0];if(f){$('#source').value=await f.text();run();}}); $('#sample').addEventListener('change',e=>{if(e.target.value){$('#source').value=samples[e.target.value];run();}}); $('#json').addEventListener('click',()=>download('rowproof-audit.json',JSON.stringify({...latest,cleaned:undefined},null,2),'application/json')); $('#clean').addEventListener('click',()=>download('rowproof-normalized.csv',stringifyCsv(latest.cleaned,latest.delimiter),'text/csv'));
